FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Install dependencies. Include development dependencies.
RUN npm install
RUN npm install -g @nestjs/cli

COPY . .

EXPOSE 3001

CMD ["npm", "run", "start:dev"]
