version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - data-arch-labs-network-dev

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - data-arch-labs-network-dev
    command: npm run start:dev

volumes:
  postgres_data_dev:

networks:
  data-arch-labs-network-dev:
    driver: bridge
